-- ============================================================
-- Migration 002: FODMAP ingredients table
-- ============================================================
-- Creates a publicly-readable table of FODMAP ingredient data
-- with bilingual translations (English + Russian).
-- Based on Monash University FODMAP research data.
-- ============================================================

CREATE TABLE IF NOT EXISTS fodmap_ingredients (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tier text NOT NULL CHECK (tier IN ('low', 'moderate', 'high')),
  translations jsonb NOT NULL, -- { "en": "carrot", "ru": "морковь" }
  notes jsonb            -- { "en": "safe in 75g serves", "ru": "безопасно до 75г" }
);

-- Make it publicly readable (no auth needed to look up FODMAP info)
ALTER TABLE fodmap_ingredients ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public read" ON fodmap_ingredients
  FOR SELECT USING (true);

-- ============================================================
-- Seed data — 230 ingredients across all categories
-- ============================================================

INSERT INTO fodmap_ingredients (tier, translations, notes) VALUES

-- ── Vegetables ──────────────────────────────────────────────
('low',      '{"en":"alfalfa sprouts","ru":"ростки люцерны"}', NULL),
('low',      '{"en":"bamboo shoots","ru":"побеги бамбука"}', NULL),
('low',      '{"en":"bean sprouts","ru":"ростки фасоли"}', NULL),
('low',      '{"en":"bok choy","ru":"бок-чой"}', '{"en":"Up to 1 cup","ru":"До 1 чашки"}'),
('low',      '{"en":"broccoli","ru":"брокколи"}', '{"en":"Up to 3/4 cup; larger amounts are high","ru":"До 3/4 чашки; в большем количестве — высокое"}'),
('low',      '{"en":"broccoli florets","ru":"соцветия брокколи"}', '{"en":"Up to 3/4 cup","ru":"До 3/4 чашки"}'),
('moderate', '{"en":"broccolini","ru":"броколини"}', '{"en":"1/2 cup is moderate","ru":"1/2 чашки — умеренное"}'),
('high',     '{"en":"brussels sprouts","ru":"брюссельская капуста"}', '{"en":"High in fructans and GOS","ru":"Высокое содержание фруктанов и ГОС"}'),
('high',     '{"en":"butternut squash","ru":"мускатная тыква"}', '{"en":"High in fructans above 1/4 cup","ru":"Высокое содержание фруктанов при порции более 1/4 чашки"}'),
('low',      '{"en":"cabbage (green)","ru":"капуста (белокочанная)"}', '{"en":"Up to 3/4 cup","ru":"До 3/4 чашки"}'),
('low',      '{"en":"cabbage (red)","ru":"капуста (краснокочанная)"}', NULL),
('low',      '{"en":"capsicum (red bell pepper)","ru":"болгарский перец (красный)"}', NULL),
('moderate', '{"en":"capsicum (green bell pepper)","ru":"болгарский перец (зелёный)"}', '{"en":"Green pepper is higher than red","ru":"Зелёный перец содержит больше FODMAP, чем красный"}'),
('low',      '{"en":"carrot","ru":"морковь"}', NULL),
('high',     '{"en":"cauliflower","ru":"цветная капуста"}', '{"en":"High in mannitol","ru":"Высокое содержание маннита"}'),
('high',     '{"en":"celery","ru":"сельдерей"}', '{"en":"High in mannitol above 1/4 stalk","ru":"Высокое содержание маннита при порции более 1/4 стебля"}'),
('low',      '{"en":"chives","ru":"лук-резанец"}', '{"en":"Fructan-free; good onion substitute","ru":"Без фруктанов; хороший заменитель репчатого лука"}'),
('low',      '{"en":"chilli (fresh red)","ru":"перец чили (свежий красный)"}', '{"en":"Up to 1 medium","ru":"До 1 среднего"}'),
('low',      '{"en":"corn (tinned)","ru":"кукуруза (консервированная)"}', '{"en":"Up to 1/2 cup","ru":"До 1/2 чашки"}'),
('moderate', '{"en":"corn on the cob","ru":"кукуруза в початках"}', '{"en":"Half a cob is moderate","ru":"Половина початка — умеренное"}'),
('low',      '{"en":"courgette (zucchini)","ru":"кабачок (цукини)"}', NULL),
('low',      '{"en":"cucumber","ru":"огурец"}', NULL),
('low',      '{"en":"eggplant (aubergine)","ru":"баклажан"}', '{"en":"Up to 1 cup","ru":"До 1 чашки"}'),
('low',      '{"en":"fennel bulb","ru":"фенхель (луковица)"}', '{"en":"Up to 1 cup","ru":"До 1 чашки"}'),
('high',     '{"en":"garlic","ru":"чеснок"}', '{"en":"Very high in fructans; use garlic-infused oil instead","ru":"Очень высокое содержание фруктанов; используйте масло, настоянное на чесноке"}'),
('low',      '{"en":"garlic-infused olive oil","ru":"оливковое масло с чесноком"}', '{"en":"Fructans do not transfer to oil","ru":"Фруктаны не переходят в масло"}'),
('low',      '{"en":"green beans","ru":"стручковая фасоль"}', '{"en":"Up to 15 beans","ru":"До 15 стручков"}'),
('low',      '{"en":"kale","ru":"кале (листовая капуста)"}', '{"en":"Up to 1 cup","ru":"До 1 чашки"}'),
('low',      '{"en":"leek (green tops only)","ru":"лук-порей (только зелёная часть)"}', '{"en":"Only the dark green part; white is high","ru":"Только тёмно-зелёная часть; белая часть — высокое"}'),
('high',     '{"en":"leek (white part)","ru":"лук-порей (белая часть)"}', '{"en":"High in fructans","ru":"Высокое содержание фруктанов"}'),
('low',      '{"en":"lettuce (iceberg)","ru":"салат (айсберг)"}', NULL),
('low',      '{"en":"lettuce (butter)","ru":"салат (масляный)"}', NULL),
('high',     '{"en":"mushroom (button)","ru":"шампиньоны"}', '{"en":"High in mannitol","ru":"Высокое содержание маннита"}'),
('low',      '{"en":"mushroom (oyster)","ru":"вешенки"}', '{"en":"Up to 1 cup","ru":"До 1 чашки"}'),
('high',     '{"en":"mushroom (canned)","ru":"грибы (консервированные)"}', '{"en":"High in mannitol","ru":"Высокое содержание маннита"}'),
('low',      '{"en":"olives","ru":"оливки"}', NULL),
('high',     '{"en":"onion (brown/white)","ru":"лук репчатый (коричневый/белый)"}', '{"en":"Very high in fructans; avoid","ru":"Очень высокое содержание фруктанов; избегайте"}'),
('low',      '{"en":"onion (spring/scallion, green tops)","ru":"лук зелёный (перо)"}', NULL),
('high',     '{"en":"onion (spring/scallion, white bulb)","ru":"лук зелёный (белая луковица)"}', NULL),
('low',      '{"en":"parsnip","ru":"пастернак"}', NULL),
('moderate', '{"en":"peas (green, canned)","ru":"горошек (зелёный, консервированный)"}', '{"en":"GOS; up to 1/4 cup is low","ru":"ГОС; до 1/4 чашки — низкое"}'),
('moderate', '{"en":"peas (snow peas)","ru":"стручковый горох"}', '{"en":"Up to 5 pods","ru":"До 5 стручков"}'),
('low',      '{"en":"potato","ru":"картофель"}', NULL),
('low',      '{"en":"pumpkin (canned)","ru":"тыква (консервированная)"}', '{"en":"Up to 1/4 cup","ru":"До 1/4 чашки"}'),
('low',      '{"en":"radish","ru":"редис"}', NULL),
('low',      '{"en":"rocket (arugula)","ru":"руккола"}', NULL),
('low',      '{"en":"silverbeet (chard)","ru":"мангольд"}', NULL),
('low',      '{"en":"spinach (baby)","ru":"шпинат (молодой)"}', NULL),
('low',      '{"en":"spinach (frozen)","ru":"шпинат (замороженный)"}', NULL),
('moderate', '{"en":"sweet potato","ru":"батат"}', '{"en":"Up to 1/2 cup; larger amounts are high","ru":"До 1/2 чашки; в большем количестве — высокое"}'),
('low',      '{"en":"tomato (cherry)","ru":"томаты черри"}', '{"en":"Up to 5 tomatoes","ru":"До 5 томатов"}'),
('low',      '{"en":"tomato (common)","ru":"томат (обычный)"}', '{"en":"Up to 1 medium","ru":"До 1 среднего"}'),
('low',      '{"en":"tomato (canned, chopped)","ru":"томаты (консервированные, нарезанные)"}', '{"en":"Up to 1/2 cup","ru":"До 1/2 чашки"}'),
('low',      '{"en":"turnip","ru":"репа"}', NULL),
('low',      '{"en":"watercress","ru":"водяной кресс"}', NULL),
('low',      '{"en":"zucchini","ru":"кабачок"}', NULL),

-- ── Fruits ──────────────────────────────────────────────────
('high',     '{"en":"apple","ru":"яблоко"}', '{"en":"High in fructose and sorbitol","ru":"Высокое содержание фруктозы и сорбита"}'),
('moderate', '{"en":"avocado","ru":"авокадо"}', '{"en":"Up to 1/8 of a whole avocado is low","ru":"До 1/8 целого авокадо — низкое"}'),
('high',     '{"en":"banana (ripe)","ru":"банан (спелый)"}', '{"en":"Ripe bananas are high; unripe is low","ru":"Спелые бананы — высокое; незрелые — низкое"}'),
('low',      '{"en":"banana (unripe)","ru":"банан (незрелый)"}', NULL),
('high',     '{"en":"blackberries","ru":"ежевика"}', '{"en":"High in excess fructose","ru":"Высокое содержание свободной фруктозы"}'),
('low',      '{"en":"blueberries","ru":"черника"}', '{"en":"Up to 1/4 cup","ru":"До 1/4 чашки"}'),
('moderate', '{"en":"cantaloupe (rockmelon)","ru":"дыня-канталупа"}', '{"en":"1/4 cup is moderate","ru":"1/4 чашки — умеренное"}'),
('high',     '{"en":"cherries","ru":"вишня/черешня"}', '{"en":"High in sorbitol","ru":"Высокое содержание сорбита"}'),
('low',      '{"en":"clementine","ru":"клементин"}', '{"en":"Up to 2 small","ru":"До 2 маленьких"}'),
('low',      '{"en":"cranberries (dried)","ru":"клюква (сушёная)"}', '{"en":"Up to 1 tbsp","ru":"До 1 ст. л."}'),
('low',      '{"en":"dragon fruit","ru":"питайя (драконий фрукт)"}', NULL),
('low',      '{"en":"grapes (green)","ru":"виноград (зелёный)"}', '{"en":"Up to 1 cup","ru":"До 1 чашки"}'),
('moderate', '{"en":"grapefruit","ru":"грейпфрут"}', '{"en":"Up to 1/2 grapefruit","ru":"До 1/2 грейпфрута"}'),
('high',     '{"en":"honeydew melon","ru":"медовая дыня"}', '{"en":"High in mannitol","ru":"Высокое содержание маннита"}'),
('low',      '{"en":"kiwi fruit","ru":"киви"}', '{"en":"Up to 2 small","ru":"До 2 маленьких"}'),
('low',      '{"en":"lemon juice","ru":"лимонный сок"}', NULL),
('low',      '{"en":"lime juice","ru":"сок лайма"}', NULL),
('low',      '{"en":"mandarin","ru":"мандарин"}', '{"en":"Up to 2 small","ru":"До 2 маленьких"}'),
('high',     '{"en":"mango","ru":"манго"}', '{"en":"High in excess fructose","ru":"Высокое содержание свободной фруктозы"}'),
('high',     '{"en":"nectarine","ru":"нектарин"}', '{"en":"High in sorbitol","ru":"Высокое содержание сорбита"}'),
('low',      '{"en":"orange","ru":"апельсин"}', '{"en":"Up to 1 medium","ru":"До 1 среднего"}'),
('low',      '{"en":"papaya (pawpaw)","ru":"папайя"}', '{"en":"Up to 1 cup","ru":"До 1 чашки"}'),
('low',      '{"en":"passionfruit","ru":"маракуйя"}', '{"en":"Up to 2","ru":"До 2 штук"}'),
('high',     '{"en":"peach","ru":"персик"}', '{"en":"High in sorbitol and fructose","ru":"Высокое содержание сорбита и фруктозы"}'),
('high',     '{"en":"pear","ru":"груша"}', '{"en":"Very high in sorbitol and fructose","ru":"Очень высокое содержание сорбита и фруктозы"}'),
('low',      '{"en":"pineapple","ru":"ананас"}', '{"en":"Up to 1 cup","ru":"До 1 чашки"}'),
('high',     '{"en":"plum","ru":"слива"}', '{"en":"High in sorbitol","ru":"Высокое содержание сорбита"}'),
('moderate', '{"en":"pomegranate seeds","ru":"зёрна граната"}', '{"en":"1/4 cup is moderate","ru":"1/4 чашки — умеренное"}'),
('low',      '{"en":"raspberry","ru":"малина"}', '{"en":"Up to 30 berries (1/4 cup)","ru":"До 30 ягод (1/4 чашки)"}'),
('low',      '{"en":"rhubarb","ru":"ревень"}', NULL),
('low',      '{"en":"strawberry","ru":"клубника"}', '{"en":"Up to 5 medium","ru":"До 5 средних"}'),
('high',     '{"en":"watermelon","ru":"арбуз"}', '{"en":"High in fructose and mannitol","ru":"Высокое содержание фруктозы и маннита"}'),

-- ── Grains & Bread ──────────────────────────────────────────
('low',      '{"en":"oats (rolled)","ru":"овсянка (хлопья)"}', '{"en":"Up to 1/2 cup dry","ru":"До 1/2 чашки в сухом виде"}'),
('low',      '{"en":"oats (quick cook)","ru":"овсянка (быстрого приготовления)"}', '{"en":"Up to 1/2 cup","ru":"До 1/2 чашки"}'),
('low',      '{"en":"oat bran","ru":"овсяные отруби"}', '{"en":"Up to 2 tbsp","ru":"До 2 ст. л."}'),
('low',      '{"en":"rice (white, long grain)","ru":"рис (белый, длиннозёрный)"}', NULL),
('low',      '{"en":"rice (brown)","ru":"рис (коричневый)"}', NULL),
('low',      '{"en":"rice (basmati)","ru":"рис (басмати)"}', NULL),
('low',      '{"en":"rice flour","ru":"рисовая мука"}', NULL),
('low',      '{"en":"quinoa","ru":"киноа"}', NULL),
('low',      '{"en":"buckwheat","ru":"гречка"}', '{"en":"Buckwheat flour and groats","ru":"Гречневая мука и крупа"}'),
('low',      '{"en":"millet","ru":"пшено"}', NULL),
('low',      '{"en":"cornflour (corn starch)","ru":"кукурузный крахмал"}', NULL),
('low',      '{"en":"polenta","ru":"полента"}', NULL),
('low',      '{"en":"potato flour","ru":"картофельная мука"}', NULL),
('low',      '{"en":"tapioca starch","ru":"тапиоковый крахмал"}', NULL),
('low',      '{"en":"sourdough bread (wheat, long fermented)","ru":"хлеб на закваске (пшеничный, долгого брожения)"}', '{"en":"Fructans broken down during fermentation","ru":"Фруктаны разрушаются при ферментации"}'),
('low',      '{"en":"gluten-free bread","ru":"хлеб без глютена"}', NULL),
('high',     '{"en":"wheat bread (regular)","ru":"пшеничный хлеб (обычный)"}', '{"en":"High in fructans","ru":"Высокое содержание фруктанов"}'),
('high',     '{"en":"wheat flour","ru":"пшеничная мука"}', '{"en":"High in fructans","ru":"Высокое содержание фруктанов"}'),
('high',     '{"en":"rye bread","ru":"ржаной хлеб"}', '{"en":"High in fructans","ru":"Высокое содержание фруктанов"}'),
('high',     '{"en":"barley","ru":"ячмень"}', '{"en":"High in fructans","ru":"Высокое содержание фруктанов"}'),
('high',     '{"en":"couscous","ru":"кускус"}', '{"en":"High in fructans","ru":"Высокое содержание фруктанов"}'),
('high',     '{"en":"pasta (wheat)","ru":"паста (пшеничная)"}', '{"en":"High in fructans","ru":"Высокое содержание фруктанов"}'),
('low',      '{"en":"pasta (gluten-free)","ru":"паста (без глютена)"}', NULL),
('low',      '{"en":"rice noodles","ru":"рисовая лапша"}', NULL),
('low',      '{"en":"glass noodles (mung bean)","ru":"стеклянная лапша (из маша)"}', NULL),
('low',      '{"en":"soba noodles (100% buckwheat)","ru":"соба (100% гречневая)"}', NULL),

-- ── Legumes ─────────────────────────────────────────────────
('low',      '{"en":"chickpeas (canned, rinsed)","ru":"нут (консервированный, промытый)"}', '{"en":"Up to 1/4 cup — rinsing reduces GOS significantly","ru":"До 1/4 чашки — промывание значительно снижает ГОС"}'),
('high',     '{"en":"chickpeas (dried, cooked)","ru":"нут (сушёный, варёный)"}', '{"en":"High in GOS","ru":"Высокое содержание ГОС"}'),
('low',      '{"en":"lentils (canned, rinsed)","ru":"чечевица (консервированная, промытая)"}', '{"en":"Up to 1/4 cup","ru":"До 1/4 чашки"}'),
('moderate', '{"en":"lentils (red, boiled)","ru":"чечевица (красная, варёная)"}', '{"en":"GOS; small amounts ok","ru":"ГОС; небольшие количества допустимы"}'),
('low',      '{"en":"kidney beans (canned, rinsed)","ru":"красная фасоль (консервированная, промытая)"}', '{"en":"Up to 1/4 cup","ru":"До 1/4 чашки"}'),
('high',     '{"en":"black beans","ru":"чёрная фасоль"}', '{"en":"High in GOS","ru":"Высокое содержание ГОС"}'),
('low',      '{"en":"butter beans (canned, rinsed)","ru":"лимская фасоль (консервированная, промытая)"}', '{"en":"Up to 1/4 cup","ru":"До 1/4 чашки"}'),
('low',      '{"en":"tofu (firm)","ru":"тофу (твёрдый)"}', '{"en":"Pressing removes GOS in liquid","ru":"Прессование удаляет ГОС из жидкости"}'),
('high',     '{"en":"tofu (silken)","ru":"тофу (шёлковый)"}', '{"en":"Contains high GOS","ru":"Высокое содержание ГОС"}'),
('moderate', '{"en":"edamame (frozen)","ru":"эдамаме (замороженный)"}', '{"en":"Up to 1/2 cup","ru":"До 1/2 чашки"}'),
('low',      '{"en":"tempeh","ru":"темпе"}', '{"en":"Fermentation reduces FODMAPs","ru":"Ферментация снижает содержание FODMAP"}'),

-- ── Proteins ────────────────────────────────────────────────
('low',      '{"en":"beef (lean)","ru":"говядина (нежирная)"}', NULL),
('low',      '{"en":"chicken breast","ru":"куриная грудка"}', NULL),
('low',      '{"en":"chicken thigh","ru":"куриное бедро"}', NULL),
('low',      '{"en":"lamb","ru":"баранина"}', NULL),
('low',      '{"en":"pork (lean)","ru":"свинина (нежирная)"}', NULL),
('low',      '{"en":"turkey","ru":"индейка"}', NULL),
('low',      '{"en":"tuna (canned in water)","ru":"тунец (консервированный в воде)"}', NULL),
('low',      '{"en":"salmon (fresh)","ru":"лосось (свежий)"}', NULL),
('low',      '{"en":"salmon (smoked)","ru":"лосось (копчёный)"}', NULL),
('low',      '{"en":"prawns (shrimp)","ru":"креветки"}', NULL),
('low',      '{"en":"cod (white fish)","ru":"треска (белая рыба)"}', NULL),
('low',      '{"en":"egg","ru":"яйцо"}', NULL),
('low',      '{"en":"egg white","ru":"яичный белок"}', NULL),

-- ── Dairy & Alternatives ────────────────────────────────────
('low',      '{"en":"lactose-free milk","ru":"молоко без лактозы"}', NULL),
('low',      '{"en":"almond milk (plain)","ru":"миндальное молоко (натуральное)"}', '{"en":"Up to 1 cup; check for additives","ru":"До 1 чашки; проверяйте добавки"}'),
('moderate', '{"en":"oat milk","ru":"овсяное молоко"}', '{"en":"Contains some fructans; up to 1/4 cup is ok","ru":"Содержит фруктаны; до 1/4 чашки допустимо"}'),
('high',     '{"en":"rice milk","ru":"рисовое молоко"}', '{"en":"High in free fructose","ru":"Высокое содержание свободной фруктозы"}'),
('low',      '{"en":"soy milk (made from soy protein)","ru":"соевое молоко (из соевого белка)"}', NULL),
('high',     '{"en":"soy milk (made from whole soybeans)","ru":"соевое молоко (из цельных соевых бобов)"}', '{"en":"High in GOS","ru":"Высокое содержание ГОС"}'),
('moderate', '{"en":"coconut milk (canned)","ru":"кокосовое молоко (консервированное)"}', '{"en":"Up to 1/4 cup","ru":"До 1/4 чашки"}'),
('moderate', '{"en":"coconut cream","ru":"кокосовые сливки"}', '{"en":"Up to 1/4 cup","ru":"До 1/4 чашки"}'),
('low',      '{"en":"coconut milk (carton, beverage)","ru":"кокосовое молоко (в коробке, напиток)"}', NULL),
('high',     '{"en":"regular cow milk","ru":"обычное коровье молоко"}', '{"en":"High in lactose","ru":"Высокое содержание лактозы"}'),
('low',      '{"en":"butter","ru":"сливочное масло"}', '{"en":"Negligible lactose","ru":"Незначительное содержание лактозы"}'),
('low',      '{"en":"ghee","ru":"гхи"}', NULL),
('low',      '{"en":"cream (heavy)","ru":"сливки (жирные)"}', '{"en":"Up to 2 tbsp; negligible lactose","ru":"До 2 ст. л.; незначительное содержание лактозы"}'),
('low',      '{"en":"cream cheese","ru":"сливочный сыр"}', '{"en":"Up to 2 tbsp","ru":"До 2 ст. л."}'),
('low',      '{"en":"cheddar cheese","ru":"сыр чеддер"}', '{"en":"Aged cheeses are low lactose","ru":"Выдержанные сыры содержат мало лактозы"}'),
('low',      '{"en":"parmesan cheese","ru":"сыр пармезан"}', NULL),
('low',      '{"en":"brie","ru":"сыр бри"}', NULL),
('low',      '{"en":"camembert","ru":"сыр камамбер"}', NULL),
('low',      '{"en":"feta cheese","ru":"сыр фета"}', '{"en":"Up to 1 oz / 28g","ru":"До 28 г"}'),
('low',      '{"en":"mozzarella","ru":"моцарелла"}', NULL),
('high',     '{"en":"cottage cheese","ru":"зернёный творог"}', '{"en":"High in lactose","ru":"Высокое содержание лактозы"}'),
('high',     '{"en":"ricotta","ru":"рикотта"}', '{"en":"High in lactose","ru":"Высокое содержание лактозы"}'),
('low',      '{"en":"greek yoghurt","ru":"греческий йогурт"}', '{"en":"Up to 3/4 cup — lower lactose than regular","ru":"До 3/4 чашки — меньше лактозы, чем в обычном"}'),
('high',     '{"en":"regular yoghurt","ru":"обычный йогурт"}', '{"en":"High in lactose","ru":"Высокое содержание лактозы"}'),
('low',      '{"en":"lactose-free yoghurt","ru":"йогурт без лактозы"}', NULL),
('high',     '{"en":"ice cream (regular)","ru":"мороженое (обычное)"}', '{"en":"High in lactose","ru":"Высокое содержание лактозы"}'),
('low',      '{"en":"sorbet","ru":"сорбет"}', '{"en":"Check for high fructose corn syrup","ru":"Проверяйте наличие кукурузного сиропа с высоким содержанием фруктозы"}'),

-- ── Nuts & Seeds ────────────────────────────────────────────
('low',      '{"en":"almonds","ru":"миндаль"}', '{"en":"Up to 10 nuts","ru":"До 10 орехов"}'),
('low',      '{"en":"brazil nuts","ru":"бразильский орех"}', '{"en":"Up to 10 nuts","ru":"До 10 орехов"}'),
('low',      '{"en":"chia seeds","ru":"семена чиа"}', '{"en":"Up to 2 tbsp","ru":"До 2 ст. л."}'),
('low',      '{"en":"flaxseed (linseed)","ru":"семена льна"}', '{"en":"Up to 1 tbsp","ru":"До 1 ст. л."}'),
('moderate', '{"en":"hazelnuts","ru":"фундук"}', '{"en":"Up to 10 nuts","ru":"До 10 орехов"}'),
('low',      '{"en":"hemp seeds","ru":"семена конопли"}', NULL),
('low',      '{"en":"macadamia nuts","ru":"орехи макадамия"}', NULL),
('low',      '{"en":"peanuts","ru":"арахис"}', '{"en":"Up to 32 nuts","ru":"До 32 орехов"}'),
('low',      '{"en":"peanut butter (no additives)","ru":"арахисовое масло (без добавок)"}', '{"en":"Up to 2 tbsp","ru":"До 2 ст. л."}'),
('low',      '{"en":"pecans","ru":"орехи пекан"}', '{"en":"Up to 10 halves","ru":"До 10 половинок"}'),
('low',      '{"en":"pine nuts","ru":"кедровые орехи"}', '{"en":"Up to 1 tbsp","ru":"До 1 ст. л."}'),
('high',     '{"en":"pistachios","ru":"фисташки"}', '{"en":"High in fructans and GOS","ru":"Высокое содержание фруктанов и ГОС"}'),
('low',      '{"en":"pumpkin seeds","ru":"тыквенные семечки"}', '{"en":"Up to 2 tbsp","ru":"До 2 ст. л."}'),
('low',      '{"en":"sesame seeds","ru":"кунжут"}', '{"en":"Up to 1 tbsp","ru":"До 1 ст. л."}'),
('low',      '{"en":"sunflower seeds","ru":"семена подсолнечника"}', '{"en":"Up to 2 tbsp","ru":"До 2 ст. л."}'),
('low',      '{"en":"tahini","ru":"тахини"}', '{"en":"Up to 2 tbsp","ru":"До 2 ст. л."}'),
('low',      '{"en":"walnuts","ru":"грецкие орехи"}', '{"en":"Up to 10 halves","ru":"До 10 половинок"}'),
('high',     '{"en":"cashews","ru":"кешью"}', '{"en":"High in GOS and fructans","ru":"Высокое содержание ГОС и фруктанов"}'),

-- ── Condiments, Sauces & Oils ───────────────────────────────
('low',      '{"en":"mayonnaise (plain)","ru":"майонез (простой)"}', NULL),
('low',      '{"en":"mustard (plain)","ru":"горчица (простая)"}', NULL),
('low',      '{"en":"soy sauce","ru":"соевый соус"}', '{"en":"Up to 2 tbsp; gluten-free soy (tamari) is also low","ru":"До 2 ст. л.; соевый соус без глютена (тамари) тоже низкое"}'),
('low',      '{"en":"tamari (gluten-free soy sauce)","ru":"тамари (соевый соус без глютена)"}', NULL),
('low',      '{"en":"fish sauce","ru":"рыбный соус"}', '{"en":"Up to 2 tbsp","ru":"До 2 ст. л."}'),
('moderate', '{"en":"oyster sauce","ru":"устричный соус"}', '{"en":"Up to 1 tbsp","ru":"До 1 ст. л."}'),
('low',      '{"en":"tomato paste","ru":"томатная паста"}', '{"en":"Up to 2 tbsp","ru":"До 2 ст. л."}'),
('low',      '{"en":"tomato sauce (ketchup)","ru":"томатный соус (кетчуп)"}', '{"en":"Up to 1 tbsp; avoid HFCS versions","ru":"До 1 ст. л.; избегайте версий с кукурузным сиропом"}'),
('moderate', '{"en":"worcestershire sauce","ru":"вустерширский соус"}', '{"en":"Check for onion/garlic ingredients","ru":"Проверяйте наличие лука и чеснока в составе"}'),
('low',      '{"en":"balsamic vinegar","ru":"бальзамический уксус"}', '{"en":"Up to 1 tbsp","ru":"До 1 ст. л."}'),
('low',      '{"en":"apple cider vinegar","ru":"яблочный уксус"}', NULL),
('low',      '{"en":"olive oil","ru":"оливковое масло"}', NULL),
('low',      '{"en":"coconut oil","ru":"кокосовое масло"}', NULL),
('low',      '{"en":"vegetable oil","ru":"растительное масло"}', NULL),
('low',      '{"en":"maple syrup","ru":"кленовый сироп"}', '{"en":"Up to 2 tbsp","ru":"До 2 ст. л."}'),
('high',     '{"en":"honey","ru":"мёд"}', '{"en":"High in excess fructose","ru":"Высокое содержание свободной фруктозы"}'),
('moderate', '{"en":"golden syrup","ru":"золотой сироп"}', NULL),
('low',      '{"en":"sugar (white, cane)","ru":"сахар (белый, тростниковый)"}', '{"en":"50:50 glucose:fructose ratio is safe","ru":"Соотношение 50:50 глюкозы и фруктозы безопасно"}'),
('low',      '{"en":"brown sugar","ru":"коричневый сахар"}', NULL),
('low',      '{"en":"stevia","ru":"стевия"}', NULL),
('high',     '{"en":"sorbitol (sweetener)","ru":"сорбит (подсластитель)"}', '{"en":"Polyol sweetener — avoid","ru":"Полиол-подсластитель — избегайте"}'),
('high',     '{"en":"xylitol (sweetener)","ru":"ксилит (подсластитель)"}', '{"en":"Polyol sweetener — avoid","ru":"Полиол-подсластитель — избегайте"}'),
('low',      '{"en":"dark chocolate (70%+)","ru":"горький шоколад (70%+)"}', '{"en":"Up to 30g; lower sugar varieties preferred","ru":"До 30 г; предпочтительнее сорта с меньшим содержанием сахара"}'),
('high',     '{"en":"milk chocolate","ru":"молочный шоколад"}', '{"en":"High in lactose and excess fructose","ru":"Высокое содержание лактозы и свободной фруктозы"}'),

-- ── Herbs & Spices ──────────────────────────────────────────
('low',      '{"en":"basil (fresh)","ru":"базилик (свежий)"}', NULL),
('low',      '{"en":"bay leaf","ru":"лавровый лист"}', NULL),
('low',      '{"en":"chilli powder","ru":"молотый чили"}', NULL),
('low',      '{"en":"cinnamon","ru":"корица"}', NULL),
('low',      '{"en":"coriander (cilantro)","ru":"кориандр (кинза)"}', NULL),
('low',      '{"en":"cumin","ru":"зира (тмин)"}', NULL),
('low',      '{"en":"dill","ru":"укроп"}', NULL),
('low',      '{"en":"ginger (fresh)","ru":"имбирь (свежий)"}', NULL),
('low',      '{"en":"ginger (ground)","ru":"имбирь (молотый)"}', NULL),
('low',      '{"en":"mint (fresh)","ru":"мята (свежая)"}', NULL),
('low',      '{"en":"oregano","ru":"орегано"}', NULL),
('low',      '{"en":"paprika","ru":"паприка"}', NULL),
('low',      '{"en":"parsley","ru":"петрушка"}', NULL),
('low',      '{"en":"pepper (black)","ru":"перец (чёрный)"}', NULL),
('low',      '{"en":"rosemary","ru":"розмарин"}', NULL),
('low',      '{"en":"sage","ru":"шалфей"}', NULL),
('low',      '{"en":"salt","ru":"соль"}', NULL),
('low',      '{"en":"thyme","ru":"тимьян"}', NULL),
('low',      '{"en":"turmeric","ru":"куркума"}', NULL),
('low',      '{"en":"vanilla extract","ru":"экстракт ванили"}', NULL),
('high',     '{"en":"garlic powder","ru":"чесночный порошок"}', '{"en":"High in fructans — avoid; use garlic-infused oil","ru":"Высокое содержание фруктанов — избегайте; используйте масло с чесноком"}'),
('high',     '{"en":"onion powder","ru":"луковый порошок"}', '{"en":"High in fructans — avoid","ru":"Высокое содержание фруктанов — избегайте"}');
